name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /root/my-app
            git pull
            docker stop my-app || true
            docker rm my-app || true
            docker build -t my-app .
            docker run -d -p 8080:8080 --name my-app my-app
